[package]
name = "futures-map"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = ""
repository = "https://github.com/dariusc93/futures-map"
authors = ["Darius Clark"]
exclude = [".gitignore"]


[dependencies]
futures = "0.3.30"
pin-project = "1.1.5"